### ISSUE TITLE
Build erros: node-gyp build

### ISSUE THREAD

**Issue by EngelEatos** [pinkipi/tera-crypto#1]
hi,
I'm new to NodeJs - hope you can help me.
I' trying to make https://github.com/NullKZ/tera-cli work.
It's relying on a fork of your tera-crypto - same error.
Is my way correct? just `npm install` inside folder.

[logfile.log](https://github.com/pinkipi/tera-crypto/files/1978878/mybestlog.log)
hope you can  help me - thanks

**Comment by pinkipi** [comment]
Compilation on GCC was broken, that should be fixed now.

Edit `tera-cli/package.json` and switch tera-proxy-game over to my repo (`github:pinkipi/tera-proxy-game`), then run `npm install` again.
